package server.restCommon;

public enum NotificationRest {
    BASKETUPDATE,RENTMADE,RENTRETURNED,BOOKSADDED,BASKETUPDATED
    //to be continued
    //for admin
    ,SUBSCRIBERREGISTERED,LIBRARIANADDED,LIBRARIANREMOVED,BOOKSREMOVED,BOOKSUPDATED
,LIBRARIANUPDATED,SUBSCRIBARREMOVED}
